baseURL = "http://example.org/"
languageCode = "en-us"
title = "Git 101"


theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "solarized"
highlight_theme = "solarized-dark"
slide_number = true
transition = "slide"
